version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: elastic_search
      POSTGRES_PASSWORD: elastic_search
      POSTGRES_DB: elastic_search
    ports:
      - '5440:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack .security.enrollment.enabled=false
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  elasticsearch-data: