
spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200
  datasource:
    url: jdbc:postgresql://localhost:5440/elastic_search
    username: elastic_search
    password: elastic_search
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: closeSea
    password: closeSeaP@ssword
  kafka:
    bootstrap-servers: localhost:9094,localhost:19094,localhost:29094
    consumer:
      group-id: elastic-group
      auto-offset-reset: earliest
  sql:
    init:
      schema-locations: classpath:org/springframework/batch/core/schema-postgresql.sql
      mode: never
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  data:
    redis:
      cluster:
        nodes: localhost:6379,localhost:6380,localhost:6381,localhost:6382,localhost:6383,localhost:6384,localhost:6385,localhost:6386,localhost:6387,localhost:6388
        max-redirects: 3
        password: bitnami
        timeout: 500ms
        connect-ip: localhost
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
logging:
  level:
    org.springframework.batch: DEBUG