package com.api.ealsticsearch.enums

enum class ChainType{
    ETHEREUM_MAINNET,
    LINEA_MAINNET,
    LINEA_SEPOLIA,
    POLYGON_MAINNET,
    ETHEREUM_HOLESKY,
    ETHEREUM_SEPOLIA,
    POLYGON_AMOY,
}

enum class ContractType{
    ERC1155,
    ERC721
}

enum class OrderStatusType { PENDING,FAILED,CANCELD,COMPLETED }

enum class StatusType { RESERVATION, ACTIVED, RESERVATION_CANCEL, CANCEL, EXPIRED,LISTING, AUCTION,LEDGER }

enum class OrderType { LISTING, AUCTION }

enum class AGGREGATIONS_TYPE { ONE_HOURS, SIX_HOURS, ONE_DAY, SEVEN_DAY }